---
title: "Class 12"
author: "Natalie McGrath"
date: "2026-10-05"
output: 
  html_document:
    toc:TRUE 
    toc_float: TRUE 
    number_sections: TRUE 
    code_download: TRUE 
    code_folding: show 
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plane crash info example 

```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

#How many <table> elements are on the page?
crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

crash_df = crash_tables[[1]]
crash_df

#From a cleaning perspective, there are several things that can be changed 

# [1] replace the colnames with the first row 
# [2] have better column types(date being a data instead of chr)
# [3] There are possible things you can do to clean the data within columns: e.g split columns that contain multiple pieces of information 
# Column 4: has fatalities/ # of passengers(ground fatalities)

#For todays class, we fill focus on the first two 
colnames(crash_df) = crash_df[1,]
#then delete first row 
crash_df = crash_df[-1,]

crash_df = crash_df |> 
  dplyr::mutate(Date = lubridate::dmy(Date))

head(crash_df)


```
```{r}
page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements("Dreadnought") |>
  rvest::html_text2()

length(classes)   # check this first: one per card

#From clicking on the cite, we saw that it changes by 50 

base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351, by = 50)
pages = vector("list", length(starts))
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |> rvest::html_text2(),
    value = pg |> rvest::html_elements("span.salvage-value") |>
      rvest::html_text2() |> stringr::str_remove("MCr")
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?
registry |> dplyr::filter(class == "dreadnought") |> 
  dplyr::mutate(value = as.numeric(value)) -> dreadnoughts_df 
sum(dreadnoughts_df$value)
```

## Structured Text Extraction 

### Course Information 
```{r}
chat = ellmer:: chat_openai(model = "gpt-5.6-luna"
    params = ellmer:: params(reasoning_effort = "none") )
isa125_text = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |> 
  rvest::html_element("#sc_sccouresdesc > div:nth-child(1)") |> rvest::html_text2()

#chat$chat_structured(
  #isa125_text, 
  #type = ellmer::type_object(
    #name = ellmer:: type_string(
      #description = Name of the course. For example "ISA 235. Information Technology and the Intelligent Enterprise. Do not include the parantheses for the credit hour and do not end with a period"
    
```

